- id: schemacrawler.tools.linter.LinterForeignKeyWithNoIndexes
  run: false

- id: schemacrawler.tools.linter.LinterForeignKeyMismatch
  run: true

- id: schemacrawler.tools.linter.LinterRedundantIndexes
  run: true

- id: schemacrawler.tools.linter.LinterTableWithNoPrimaryKey
  run: true
  
- id: schemacrawler.tools.linter.LinterTableWithNoSurrogatePrimaryKey
  run: false

- id: schemacrawler.tools.linter.LinterTableWithNoRemarks
  run: true

- id: schemacrawler.tools.linter.LinterTableEmpty
  run: true

- id: schemacrawler.tools.linter.LinterTableWithBadlyNamedColumns
  run: true
  table-exclusion-pattern: ".*\\.about$"
  config:
    bad-column-names: ".*\\.[^a-z0-9_].*"

- id: schemacrawler.tools.linter.LinterTableWithQuotedNames
  run: true
  table-exclusion-pattern: ".*\\.about$"

- id: schemacrawler.tools.linter.LinterCatalogSql
  run: true
  config:
    message: "Invalid table name. Should not contain special characters or uppercase"
    sql: |
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'main'
      AND table_name !~ '^[a-z][a-z0-9_]*$'
      LIMIT 1

- id: schemacrawler.tools.linter.LinterCatalogSql
  run: true
  config:
    message: "id column must end with _id"
    sql: |
      SELECT table_name || '.' || column_name
      FROM information_schema.columns
      WHERE table_schema = 'main'
      AND column_name ~ '^id_.*'
      LIMIT 1