name: Compute Version
on:
  workflow_call:
    outputs:
      new_version:
        value: ${{ jobs.compute.outputs.new_version }}
      unique_branch:
        value: ${{ jobs.compute.outputs.unique_branch }}

jobs:
  compute:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      unique_branch: ${{ steps.version.outputs.unique_branch }}
    steps:
      - name: Compute version and branch
        id: version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LAST=$(gh release view --json tagName -q .tagName 2>/dev/null || echo "v0.0")
          echo "<" + $LAST + ">"
          VERSION=${LAST#v}

          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          
          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            if echo "$LAST" | grep -q "develop"; then
              DEV_NUM=${LAST#*develop.}
              DEV_NUM=$((DEV_NUM + 1))
            else
              DEV_NUM=1
              MINOR=$((MINOR + 1))
            fi
            
            UNIQUE_BRANCH="develop-data-update-${{ github.run_number }}"
            NEW="v${MAJOR}.$((MINOR))-develop.$DEV_NUM"
          else
            UNIQUE_BRANCH="main-data-update-${{ github.run_number }}"
            NEW="v${MAJOR}.$((MINOR + 1))"
          fi
          echo "<" + $NEW + ">"
          echo "new_version=$NEW" >> $GITHUB_OUTPUT
          echo "unique_branch=$UNIQUE_BRANCH" >> $GITHUB_OUTPUT
