name: CD - Déploiement GitHub Pages

on:
  workflow_run:
    workflows: [ "CI - Génération des fichiers et Release" ]
    types: [ completed ]
    branches: [ main ]

permissions:
  contents: write
  pages: read

jobs:
  deploy:
    name: Deploy Hugo site
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0

      - name: Install Task
        uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa

      - name: Setup DuckDB action
        uses: opt-nc/setup-duckdb-action@c64cd61a8a0af98f7d5d8b45e9dc332d250cd217

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.14.5'

      - name: Install Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78
        with:
          hugo-version: '0.163.0'

      - name: Generate DuckDB database
        run: task duckdb

      - id: pages
        name: Configure Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      - name: Generate Hugo site
        env:
          HUGO_BASE_URL: ${{ steps.pages.outputs.base_url }}
          SITE_ENV: github-pages
        run: task site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site/public
