name: CI pour la branche develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
jobs:
  compute:
    uses: ./.github/workflows/compute-version.yml
    secrets: inherit
    
  build:
    name: DuckDB Integration
    runs-on: ubuntu-latest
    needs: compute
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: opt-nc/setup-duckdb-action@v1.2.6
      
      - name: Load DuckDB database
        run: |
          mkdir dist
          duckdb dist/gem.duckdb < src/duck.sql

      - name: update output repository and push to develop
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UNIQUE_BRANCH="${{ needs.compute.outputs.unique_branch }}"
          NEW="${{ needs.compute.outputs.new_version }}"
          
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git fetch origin
          git checkout -b $UNIQUE_BRANCH
          
          git add data/output/*.csv
          git commit -m "Updated output's files"
          git push origin $UNIQUE_BRANCH

          gh pr create --head $UNIQUE_BRANCH --base develop --title "Updated develop branch's output's files" --body "Cette Pull Request a été générée automatiquement par la CI. Elle contient les fichiers CSV mis à jour."

          gh pr merge $UNIQUE_BRANCH --merge --delete-branch

          gh release create $NEW --title "prerelease $NEW" --notes "Mise à jour automatique du référentiel d'export des métiers." --target develop dist/gem.duckdb
