name: CI pour la branche develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  compute:
    uses: ./.github/workflows/compute-version.yml
    secrets: inherit
    
  generate_duckdb:
    name: Generating DuckDB File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: opt-nc/setup-duckdb-action@v1.2.6
      
      - name: Load DuckDB database
        run: |
          mkdir dist
          mkdir -p data/output/csv
          duckdb dist/ref-metiers-opt-nc.duckdb < src/duck.sql
          
      - name: Upload DuckDB artifact
        uses: actions/upload-artifact@v4
        with:
          name: duckdb-file
          path: dist/ref-metiers-opt-nc.duckdb

      - name: Upload CSV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: csv-files
          path: data/output/csv/

  generate_sqlite:
    name: Generating SQLite File
    runs-on: ubuntu-latest
    needs: generate_duckdb
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download CSV artifacts
        uses: actions/download-artifact@v4
        with:
          name: csv-files
          path: data/output/csv/

      - name: Load SQLite database
        run: |
          mkdir dist
          sqlite3 dist/ref-metiers-opt-nc.sqlite < src/sqlite.sql

      - id: schemacrawler
        name: Run SchemaCrawler on SQLite
        uses: schemacrawler/SchemaCrawler-Action@v17.11.1
        with:
          entrypoint: /schemacrawler.sh
          args: >
            --server=sqlite
            --database=dist/schema_export.sqlite
            --info-level=standard
            --command=schema
            --table-types=TABLE
            --output-format=html
            --output-file=dist/ref-metiers-opt-nc-schema.html
                
      - name: Upload SQLite artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-file
          path: dist/ref-metiers-opt-nc.sqlite

  generate_prerelease:
    name: Generating Pre Release
    runs-on: ubuntu-latest
    needs: [ compute, generate_duckdb, generate_sqlite ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Download DuckDB artifact
        uses: actions/download-artifact@v4
        with:
          name: duckdb-file
          path: dist
          
      - name: Download SQLite artifact
        uses: actions/download-artifact@v4
        with:
          name: sqlite-file
          path: dist

      - name: Download CSV artifacts
        uses: actions/download-artifact@v4
        with:
          name: csv-files
          path: data/output/csv/

      - name: Push CSV outputs to develop using PR
        run: |
          UNIQUE_BRANCH="${{ needs.compute.outputs.unique_branch }}"

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch origin
          git checkout -b $UNIQUE_BRANCH
          
          git stash
          git merge origin/develop --no-edit -X theirs || true
          git stash pop || true

          git add -f data/output/csv/about.csv
          git add -f data/output/csv/categorie_detention.csv
          git add -f data/output/csv/competence.csv
          git add -f data/output/csv/competence_utilisateur.csv
          git add -f data/output/csv/famille_metier.csv
          git add -f data/output/csv/gem_competence.csv
          git add -f data/output/csv/gem_metier.csv
          git add -f data/output/csv/gem_metier_competence.csv
          git add -f data/output/csv/groupe_competence.csv
          git add -f data/output/csv/metier.csv
          git add -f data/output/csv/metier_competence.csv
          git add -f data/output/csv/niveau_description_competence.csv
          git add -f data/output/csv/referentiel_competence.csv
          git add -f data/output/csv/statut_metier.csv

          git commit -m "Updated output's files"
          git push origin $UNIQUE_BRANCH
          gh pr create --head $UNIQUE_BRANCH --base develop --title "Updated develop branch's output's files" --body "Cette Pull Request a été générée automatiquement par la CI. Elle contient les fichiers CSV mis à jour."
          gh pr merge $UNIQUE_BRANCH --merge --delete-branch

      - name: Create Pre Release
        run: |
          NEW="${{ needs.compute.outputs.new_version }}"
          
          gh release create $NEW --title "prerelease $NEW" --notes "Mise à jour automatique du référentiel d'export des métiers." --target develop dist/ref-metiers-opt-nc.duckdb dist/ref-metiers-opt-nc.sqlite
          
