name: CI - Vérification des Pull Requests

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  generate_duckdb:
    name: Verify Generation Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositories
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Install Task
        uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa

      - name: Setup DuckDB action
        uses: opt-nc/setup-duckdb-action@c64cd61a8a0af98f7d5d8b45e9dc332d250cd217

      - id: install-schemacrawler
        name: Install SchemaCrawler
        uses: schemacrawler/SchemaCrawler-Action@c96a1fb8e771e20e86428d04e77029c0a0a471ef

      - name: Install Graphviz to generate schemas
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Install Asciidoctor PDF via APT
        run: sudo apt-get update && sudo apt-get install -y ruby-asciidoctor-pdf

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.14.5'

      - name: Build DuckDB and SQLite databases
        run: |
          task duckdb
          task sqlite

      - name: Generating SchemaCrawler schemas
        shell: bash
        env:
          SDKMAN_DIR: ${{ github.workspace }}/.sdkman
        run: |
          source "$SDKMAN_DIR/bin/sdkman-init.sh"
          task schema

      - name: Generate documentation
        run: |
          task doc
      
          
