name: CI - Vérification des Pull Requests

on:
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: write

jobs:
  verify:
    name: Verify Generation Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositories
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0

      - name: Install Task
        uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.14.5'

      - name: Install Pandoc
        uses: pandoc/actions/setup@86321b6dd4675f5014c611e05088e10d4939e09e
        with:
          version: 3.9.0.2

      - name: Setup DuckDB action
        uses: opt-nc/setup-duckdb-action@c64cd61a8a0af98f7d5d8b45e9dc332d250cd217

      - id: install-schemacrawler
        name: Install SchemaCrawler
        uses: schemacrawler/SchemaCrawler-Local-Action@ddd39d2e1d15cf000e0b7aaa30c6f00fe6b7f15f

      - name: Install Graphviz to generate schemas
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Install Asciidoctor PDF via APT
        run: sudo apt-get update && sudo apt-get install -y ruby-asciidoctor-pdf
      
      - name: Install hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78
        with:
          hugo-version: '0.163.0'

      - name: Build DuckDB and SQLite databases
        run: |
          task duckdb
          task sqlite

      - name: Generating SchemaCrawler schemas
        shell: bash
        env:
          SDKMAN_DIR: ${{ github.workspace }}/.sdkman
        run: |
          source "$SDKMAN_DIR/bin/sdkman-init.sh"
          
          BASE_CMD="schemacrawler.sh --info-level=standard --driver=org.duckdb.DuckDBDriver --url=jdbc:duckdb:dist/ref-metiers-opt-nc.duckdb --config-file=.github/schemacrawler/config/schemacrawler.config.properties --command=schema"
          $BASE_CMD --output-format=pdf --output-file=dist/ref-metiers-opt-nc-schema.pdf
          $BASE_CMD --output-format=png --output-file=dist/ref-metiers-opt-nc-schema.png
          $BASE_CMD --output-format=html --output-file=dist/ref-metiers-opt-nc-schema.html

      - name: Generate documentation
        run: |
          task docs
      
      - id: pages
        name: Configure Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      - name: Generate Hugo site
        env:
          HUGO_BASE_URL: ${{ steps.pages.outputs.base_url }}
        run: task site
      
          
