name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: DuckDB Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: opt-nc/setup-duckdb-action@v1.2.6
      
      - name: Load DuckDB database
        run: |
          mkdir dist
          duckdb dist/gem.duckdb < src/duck.sql

      - name: update output repository and push to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UNIQUE_BRANCH="data-update-${{ github.run_number }}"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git checkout -b $UNIQUE_BRANCH
          
          git add data/output/*.csv
          git commit -m "Updated output's files"
          git push origin $UNIQUE_BRANCH

          gh pr create --head $UNIQUE_BRANCH --base main --title "Updated output's files" --body "Cette Pull Request a été générée automatiquement par la CI. Elle contient les fichiers CSV mis à jour."

          gh pr merge $UNIQUE_BRANCH --merge --delete-branch

          gh release edit v0.0 --target main --verify-tag
          gh release create v0.0 --title "Release v0.0" --notes "Mise à jour automatique du référentiel d'export des métiers." --target main --verify-tag
