name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: DuckDB Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: opt-nc/setup-duckdb-action@v1.2.6
      
      - name: Load DuckDB database
        run: |
          mkdir dist
          duckdb dist/gem.duckdb < src/duck.sql

      - name: update output repository and push to main
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/output/*.csv
          git commit -m "Updated output's files"
          git push origin HEAD
