name: CI - Génération des fichiers du Référentiel Métiers

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    outputs:
      new_release_published: ${{ steps.release.outputs.new_release_published }}
      new_release_version: ${{ steps.release.outputs.new_release_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
            @semantic-release/release-notes-generator
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate_duckdb:
    name: Generating DuckDB File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositories
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Setup DuckDB action
        uses: opt-nc/setup-duckdb-action@v1.2.6

      - name: Load DuckDB database
        run: |
          mkdir dist
          mkdir -p data/output
          duckdb dist/ref-metiers-opt-nc.duckdb < src/duck.sql

      - name: Upload DuckDB artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: duckdb-file
          path: dist/ref-metiers-opt-nc.duckdb

      - name: Upload CSV artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: csv-files
          path: data/output/csv/

  generate_sqlite:
    name: Generating SQLite File
    runs-on: ubuntu-latest
    needs: generate_duckdb
    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Download CSV artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: csv-files
          path: data/output/csv

      - name: Load SQLite database
        run: |
          mkdir dist
          mkdir -p data/output
          sqlite3 dist/ref-metiers-opt-nc.sqlite < src/sqlite.sql

      - name: Upload SQLite artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: sqlite-file
          path: dist/ref-metiers-opt-nc.sqlite

  generate_schemas:
    name: Generating DuckDB Schemas with SchemaCrawler
    runs-on: ubuntu-slim
    needs: [ generate_duckdb ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Download DuckDB artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: duckdb-file
          path: dist

      - id: install-schemacrawler
        name: Install SchemaCrawler
        uses: schemacrawler/SchemaCrawler-Local-Action@v17.11.2

      - name: Install Graphviz to generate schemas
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Generating SchemaCrawler schemas (PDF, PNG, HTML)
        shell: bash
        env:
          SDKMAN_DIR: ${{ github.workspace }}/.sdkman
        run: |
          source "$SDKMAN_DIR/bin/sdkman-init.sh"

          BASE_CMD="schemacrawler.sh --info-level=standard --driver=org.duckdb.DuckDBDriver --url=jdbc:duckdb:dist/ref-metiers-opt-nc.duckdb --config-file=.github/schemacrawler/config/schemacrawler.config.properties --command=schema"
          $BASE_CMD --output-format=pdf --output-file=dist/ref-metiers-opt-nc-schema.pdf
          $BASE_CMD --output-format=png --output-file=dist/ref-metiers-opt-nc-schema.png
          $BASE_CMD --output-format=html --output-file=dist/ref-metiers-opt-nc-schema.html

      - name: Upload SchemaCrawler assets
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: schemacrawler-assets
          path: |
            dist/ref-metiers-opt-nc-schema.pdf
            dist/ref-metiers-opt-nc-schema.png
            dist/ref-metiers-opt-nc-schema.html

  generate_documentation:
    name: Generating documentation with adoc and pdf
    runs-on: ubuntu-latest
    needs: [ generate_duckdb ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Download DuckDB artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: duckdb-file
          path: dist

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.x'

      - name: Install uv
        run: pip install uv

      - name: Install Asciidoctor PDF via APT
        run: sudo apt-get update && sudo apt-get install -y ruby-asciidoctor-pdf

      - name: Setup Python dependencies with uv
        run: |
          uv init --bare
          uv add duckdb

      - name: Generating adoc
        run: |
          mkdir -p data/output
          uv run src/generate-adoc.py

      - name: Generating PDF
        run: asciidoctor-pdf -a icons=font -a icon-set=fas -a pdf-theme=etc/themes/pdf-theme.yml data/output/doc/referentiel_metiers.adoc -o data/output/doc/referentiel_metiers.pdf

      - name: Upload documentation assets
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: documents-assets
          path: |
            data/output/doc/referentiel_metiers.pdf
            data/output/doc/referentiel_metiers.adoc

  update_output_repository:
    name: Updating output repository
    runs-on: ubuntu-latest
    needs: [ release, generate_duckdb, generate_sqlite, generate_schemas, generate_documentation ]
    if: github.event_name == 'push' && needs.release.outputs.new_release_published == 'true'
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0

      - name: Download all artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          path: artifacts

      - name: Dispatch downloaded files
        run: |
          mkdir -p dist data/output/csv data/output/doc
          
          mv artifacts/duckdb-file/* dist/
          mv artifacts/sqlite-file/* dist/
          mv artifacts/schemacrawler-assets/* dist/
          mv artifacts/csv-files/* data/output/csv/
          mv artifacts/documents-assets/* data/output/doc/
          
          rm -rf artifacts

      - name: Push CSV outputs to main using PR
        run: |
          TARGET_BRANCH="${{ github.ref_name }}"
          BRANCH_NAME="data-update-${TARGET_BRANCH}-${{ github.run_number }}"

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch origin
          git checkout -b $BRANCH_NAME

          git add data/output/csv/about.csv
          git add data/output/csv/categorie_detention.csv
          git add data/output/csv/competence.csv
          git add data/output/csv/competence_utilisateur.csv
          git add data/output/csv/famille_metier.csv
          git add data/output/csv/gem_competence.csv
          git add data/output/csv/gem_metier.csv
          git add data/output/csv/gem_metier_competence.csv
          git add data/output/csv/groupe_competence.csv
          git add data/output/csv/metier.csv
          git add data/output/csv/metier_competence.csv
          git add data/output/csv/niveau_description_competence.csv
          git add data/output/csv/referentiel_competence.csv
          git add data/output/csv/statut_metier.csv

          git commit -m "Updated output's files for $TARGET_BRANCH"
          git push origin $BRANCH_NAME
          gh pr create --head $BRANCH_NAME --base $TARGET_BRANCH --title "Updated $TARGET_BRANCH branch's output's files" --body "Cette Pull Request a été générée automatiquement par la CI. Elle contient les fichiers CSV mis à jour."
          gh pr merge $BRANCH_NAME --merge --delete-branch

      - name: Upload Release assets
        run: |
          TAG_VERSION="v${{ needs.release.outputs.new_release_version }}"
          gh release upload $TAG_VERSION dist/ref-metiers-opt-nc.duckdb dist/ref-metiers-opt-nc.sqlite dist/ref-metiers-opt-nc-schema.pdf dist/ref-metiers-opt-nc-schema.png dist/ref-metiers-opt-nc-schema.html data/output/doc/referentiel_metiers.pdf data/output/doc/referentiel_metiers.adoc